# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Append models to release

on:
  release:
    types:
      - created

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install jayvee interpreter
        run: npm install -g @jvalue/jayvee-interpreter@0.6.0

      - name: Run and zip model
        run: bash -x tools/scripts/process-model.bash src/models/battery-materials/model.jv
      - name: Upload result
        run: bash -x tools/scripts/release-model.bash build/battery-materials.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_REF: ${{ github.ref }}

      - name: Run and zip model
        run: bash -x tools/scripts/process-model.bash src/models/refractive-indices-dielectric-constants/model.jv
      - name: Upload result
        run: bash -x tools/scripts/release-model.bash build/refractive-indices-dielectric-constants.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_REF: ${{ github.ref }}

      - name: Run and zip model
        run: bash -x tools/scripts/process-model.bash src/models/semiconductor-band-gaps/model.jv
      - name: Upload result
        run: bash -x tools/scripts/release-model.bash build/semiconductor-band-gaps.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_REF: ${{ github.ref }}

      - name: Run and zip model
        run: bash -x tools/scripts/process-model.bash src/models/yield-strength-grain-size/model.jv
      - name: Upload result
        run: bash -x tools/scripts/release-model.bash build/yield-strength-grain-size.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_REF: ${{ github.ref }}

      - name: Run and zip model
        run: bash -x tools/scripts/process-model.bash src/models/thermoelectric-materials/model.jv
      - name: Upload result
        run: bash -x tools/scripts/release-model.bash build/thermoelectric-materials.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_REF: ${{ github.ref }}

      # This model does not work, see https://github.com/jvalue/jayvee/issues/603
      #- name: Run and zip model
      #  run: bash -x tools/scripts/process-model.bash src/models/thermoelectric-materials-system-identified-material-representation/model.jv
      #- name: Upload result
      #  run: bash -x tools/scripts/release-model.bash build/thermoelectric-materials-system-identified-material-representation.zip
      #  env:
      #    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    RELEASE_REF: ${{ github.ref }}